/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import static Main.main.simulacion;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSpinner;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author georg
 */
public class Simulación extends javax.swing.JFrame {

    /**
     * Creates new form Simulación
     */
    public Simulación() {
        initComponents();
        this.setLocationRelativeTo(null);
        DuracionBatalla.setValue(simulacion.getTime());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CompetidorAVT = new javax.swing.JLabel();
        cola1avatar = new javax.swing.JScrollPane();
        Cola1AVT = new javax.swing.JTextArea();
        cola2avatar = new javax.swing.JScrollPane();
        Cola2AVT = new javax.swing.JTextArea();
        cola3avatar = new javax.swing.JScrollPane();
        Cola3AVT = new javax.swing.JTextArea();
        refuerzoavatar = new javax.swing.JScrollPane();
        RefuerzoAVT = new javax.swing.JTextArea();
        cola1unshowmas = new javax.swing.JScrollPane();
        Cola1USM = new javax.swing.JTextArea();
        cola2unshowmas = new javax.swing.JScrollPane();
        Cola2USM = new javax.swing.JTextArea();
        cola3unshowmas = new javax.swing.JScrollPane();
        Cola3USM = new javax.swing.JTextArea();
        refuerzounshowmas = new javax.swing.JScrollPane();
        RefuerzoUSM = new javax.swing.JTextArea();
        HabilidadAVT = new javax.swing.JLabel();
        VidaAVT = new javax.swing.JLabel();
        AgilidadAVT = new javax.swing.JLabel();
        FuerzaAVT = new javax.swing.JLabel();
        HabilidadUSM = new javax.swing.JLabel();
        VidaUSM = new javax.swing.JLabel();
        FuerzaUSM = new javax.swing.JLabel();
        AgilidadUSM = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        EstadoIA = new javax.swing.JLabel();
        DuracionBatalla = new javax.swing.JSpinner();
        CompetidorUSM = new javax.swing.JLabel();
        NombreCompetidorAVT = new javax.swing.JLabel();
        NombreCompetidorUSM = new javax.swing.JLabel();
        colaganadoresunshowmas = new javax.swing.JScrollPane();
        ColaGanadoresUSM = new javax.swing.JTextArea();
        colaganadoresavatar = new javax.swing.JScrollPane();
        ColaGanadoresAVT = new javax.swing.JTextArea();
        VictoriasAVT = new javax.swing.JLabel();
        VictoriasUSM = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 64, -1, -1));

        CompetidorAVT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PersonajesAvatar/hama.png"))); // NOI18N
        getContentPane().add(CompetidorAVT, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, -1, -1));

        Cola1AVT.setBackground(new java.awt.Color(153, 204, 255));
        Cola1AVT.setColumns(20);
        Cola1AVT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Cola1AVT.setLineWrap(true);
        Cola1AVT.setRows(5);
        Cola1AVT.setWrapStyleWord(true);
        cola1avatar.setViewportView(Cola1AVT);

        getContentPane().add(cola1avatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 220, 80));

        Cola2AVT.setBackground(new java.awt.Color(153, 204, 255));
        Cola2AVT.setColumns(20);
        Cola2AVT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Cola2AVT.setLineWrap(true);
        Cola2AVT.setRows(5);
        Cola2AVT.setWrapStyleWord(true);
        cola2avatar.setViewportView(Cola2AVT);

        getContentPane().add(cola2avatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 220, 80));

        Cola3AVT.setBackground(new java.awt.Color(153, 204, 255));
        Cola3AVT.setColumns(20);
        Cola3AVT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Cola3AVT.setLineWrap(true);
        Cola3AVT.setRows(5);
        Cola3AVT.setWrapStyleWord(true);
        cola3avatar.setViewportView(Cola3AVT);

        getContentPane().add(cola3avatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 220, 80));

        RefuerzoAVT.setBackground(new java.awt.Color(153, 204, 255));
        RefuerzoAVT.setColumns(20);
        RefuerzoAVT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RefuerzoAVT.setLineWrap(true);
        RefuerzoAVT.setRows(5);
        RefuerzoAVT.setWrapStyleWord(true);
        refuerzoavatar.setViewportView(RefuerzoAVT);

        getContentPane().add(refuerzoavatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 220, 80));

        Cola1USM.setBackground(new java.awt.Color(255, 204, 102));
        Cola1USM.setColumns(20);
        Cola1USM.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Cola1USM.setLineWrap(true);
        Cola1USM.setRows(5);
        Cola1USM.setWrapStyleWord(true);
        cola1unshowmas.setViewportView(Cola1USM);

        getContentPane().add(cola1unshowmas, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 50, 220, 80));

        Cola2USM.setBackground(new java.awt.Color(255, 204, 102));
        Cola2USM.setColumns(20);
        Cola2USM.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Cola2USM.setLineWrap(true);
        Cola2USM.setRows(5);
        Cola2USM.setWrapStyleWord(true);
        cola2unshowmas.setViewportView(Cola2USM);

        getContentPane().add(cola2unshowmas, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 160, 220, 80));

        Cola3USM.setBackground(new java.awt.Color(255, 204, 102));
        Cola3USM.setColumns(20);
        Cola3USM.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Cola3USM.setLineWrap(true);
        Cola3USM.setRows(5);
        Cola3USM.setWrapStyleWord(true);
        cola3unshowmas.setViewportView(Cola3USM);

        getContentPane().add(cola3unshowmas, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 270, 220, 80));

        RefuerzoUSM.setBackground(new java.awt.Color(255, 204, 102));
        RefuerzoUSM.setColumns(20);
        RefuerzoUSM.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RefuerzoUSM.setLineWrap(true);
        RefuerzoUSM.setRows(5);
        RefuerzoUSM.setWrapStyleWord(true);
        refuerzounshowmas.setViewportView(RefuerzoUSM);

        getContentPane().add(refuerzounshowmas, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 380, 220, 80));

        HabilidadAVT.setText("0");
        getContentPane().add(HabilidadAVT, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, 40, -1));

        VidaAVT.setText("0");
        getContentPane().add(VidaAVT, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, 30, -1));

        AgilidadAVT.setText("0");
        getContentPane().add(AgilidadAVT, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 410, 30, -1));

        FuerzaAVT.setText("0");
        getContentPane().add(FuerzaAVT, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, 30, -1));

        HabilidadUSM.setText("0");
        getContentPane().add(HabilidadUSM, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 410, 30, 20));

        VidaUSM.setText("0");
        getContentPane().add(VidaUSM, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 410, 30, -1));

        FuerzaUSM.setText("0");
        getContentPane().add(FuerzaUSM, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 410, 30, -1));

        AgilidadUSM.setText("0");
        getContentPane().add(AgilidadUSM, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 410, 30, -1));

        jButton1.setText("Actualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 550, -1, -1));

        EstadoIA.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EstadoIA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EstadoIA.setText("jLabel3");
        getContentPane().add(EstadoIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 530, 150, -1));
        getContentPane().add(DuracionBatalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 520, 100, -1));

        CompetidorUSM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PersonajesUnShowMas/Gary.png"))); // NOI18N
        getContentPane().add(CompetidorUSM, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, -1, -1));

        NombreCompetidorAVT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        NombreCompetidorAVT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NombreCompetidorAVT.setText("jLabel1");
        getContentPane().add(NombreCompetidorAVT, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 160, -1));

        NombreCompetidorUSM.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        NombreCompetidorUSM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NombreCompetidorUSM.setText("jLabel2");
        getContentPane().add(NombreCompetidorUSM, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 150, -1));

        ColaGanadoresUSM.setBackground(new java.awt.Color(255, 204, 102));
        ColaGanadoresUSM.setColumns(20);
        ColaGanadoresUSM.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ColaGanadoresUSM.setLineWrap(true);
        ColaGanadoresUSM.setRows(5);
        ColaGanadoresUSM.setWrapStyleWord(true);
        colaganadoresunshowmas.setViewportView(ColaGanadoresUSM);

        getContentPane().add(colaganadoresunshowmas, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 500, 220, 80));

        ColaGanadoresAVT.setBackground(new java.awt.Color(153, 204, 255));
        ColaGanadoresAVT.setColumns(20);
        ColaGanadoresAVT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ColaGanadoresAVT.setLineWrap(true);
        ColaGanadoresAVT.setRows(5);
        ColaGanadoresAVT.setWrapStyleWord(true);
        colaganadoresavatar.setViewportView(ColaGanadoresAVT);

        getContentPane().add(colaganadoresavatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 220, 80));

        VictoriasAVT.setText("0");
        getContentPane().add(VictoriasAVT, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 70, 50, -1));

        VictoriasUSM.setText("0");
        getContentPane().add(VictoriasUSM, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 80, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Colorful INTERFAZ (800 x 500 px).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int duracion = (int)DuracionBatalla.getValue();
        simulacion.getAI().setDayDuration(duracion);
        simulacion.setTime(duracion);
    }//GEN-LAST:event_jButton1ActionPerformed

    public JLabel getAgilidadAVT() {
        return AgilidadAVT;
    }

    public void setAgilidadAVT(JLabel AgilidadAVT) {
        this.AgilidadAVT = AgilidadAVT;
    }

    public JLabel getAgilidadUSM() {
        return AgilidadUSM;
    }

    public void setAgilidadUSM(JLabel AgilidadUSM) {
        this.AgilidadUSM = AgilidadUSM;
    }

    public JTextArea getCola1AVT() {
        return Cola1AVT;
    }

    public void setCola1AVT(JTextArea Cola1AVT) {
        this.Cola1AVT = Cola1AVT;
    }

    public JTextArea getCola1USM() {
        return Cola1USM;
    }

    public void setCola1USM(JTextArea Cola1USM) {
        this.Cola1USM = Cola1USM;
    }

    public JTextArea getCola2AVT() {
        return Cola2AVT;
    }

    public void setCola2AVT(JTextArea Cola2AVT) {
        this.Cola2AVT = Cola2AVT;
    }

    public JTextArea getCola2USM() {
        return Cola2USM;
    }

    public void setCola2USM(JTextArea Cola2USM) {
        this.Cola2USM = Cola2USM;
    }

    public JTextArea getCola3AVT() {
        return Cola3AVT;
    }

    public void setCola3AVT(JTextArea Cola3AVT) {
        this.Cola3AVT = Cola3AVT;
    }

    public JTextArea getCola3USM() {
        return Cola3USM;
    }

    public void setCola3USM(JTextArea Cola3USM) {
        this.Cola3USM = Cola3USM;
    }

    public JTextArea getColaGanadoresAVT() {
        return ColaGanadoresAVT;
    }

    public void setColaGanadoresAVT(JTextArea ColaGanadoresAVT) {
        this.ColaGanadoresAVT = ColaGanadoresAVT;
    }

    public JTextArea getColaGanadoresUSM() {
        return ColaGanadoresUSM;
    }

    public void setColaGanadoresUSM(JTextArea ColaGanadoresUSM) {
        this.ColaGanadoresUSM = ColaGanadoresUSM;
    }

    public JLabel getCompetidorAVT() {
        return CompetidorAVT;
    }

    public void setCompetidorAVT(JLabel CompetidorAVT) {
        this.CompetidorAVT = CompetidorAVT;
    }

    public JLabel getCompetidorUSM() {
        return CompetidorUSM;
    }

    public void setCompetidorUSM(JLabel CompetidorUSM) {
        this.CompetidorUSM = CompetidorUSM;
    }

    public JSpinner getDuracionBatalla() {
        return DuracionBatalla;
    }

    public void setDuracionBatalla(JSpinner DuracionBatalla) {
        this.DuracionBatalla = DuracionBatalla;
    }

    public JLabel getEstadoIA() {
        return EstadoIA;
    }

    public void setEstadoIA(JLabel EstadoIA) {
        this.EstadoIA = EstadoIA;
    }

    public JLabel getFuerzaAVT() {
        return FuerzaAVT;
    }

    public void setFuerzaAVT(JLabel FuerzaAVT) {
        this.FuerzaAVT = FuerzaAVT;
    }

    public JLabel getFuerzaUSM() {
        return FuerzaUSM;
    }

    public void setFuerzaUSM(JLabel FuerzaUSM) {
        this.FuerzaUSM = FuerzaUSM;
    }

    public JLabel getHabilidadAVT() {
        return HabilidadAVT;
    }

    public void setHabilidadAVT(JLabel HabilidadAVT) {
        this.HabilidadAVT = HabilidadAVT;
    }

    public JLabel getHabilidadUSM() {
        return HabilidadUSM;
    }

    public void setHabilidadUSM(JLabel HabilidadUSM) {
        this.HabilidadUSM = HabilidadUSM;
    }

    public JLabel getNombreCompetidorAVT() {
        return NombreCompetidorAVT;
    }

    public void setNombreCompetidorAVT(JLabel NombreCompetidorAVT) {
        this.NombreCompetidorAVT = NombreCompetidorAVT;
    }

    public JLabel getNombreCompetidorUSM() {
        return NombreCompetidorUSM;
    }

    public void setNombreCompetidorUSM(JLabel NombreCompetidorUSM) {
        this.NombreCompetidorUSM = NombreCompetidorUSM;
    }

    public JTextArea getRefuerzoAVT() {
        return RefuerzoAVT;
    }

    public void setRefuerzoAVT(JTextArea RefuerzoAVT) {
        this.RefuerzoAVT = RefuerzoAVT;
    }

    public JTextArea getRefuerzoUSM() {
        return RefuerzoUSM;
    }

    public void setRefuerzoUSM(JTextArea RefuerzoUSM) {
        this.RefuerzoUSM = RefuerzoUSM;
    }

    public JLabel getVidaAVT() {
        return VidaAVT;
    }

    public void setVidaAVT(JLabel VidaAVT) {
        this.VidaAVT = VidaAVT;
    }

    public JLabel getVidaUSM() {
        return VidaUSM;
    }

    public void setVidaUSM(JLabel VidaUSM) {
        this.VidaUSM = VidaUSM;
    }

    public JScrollPane getCola1avatar() {
        return cola1avatar;
    }

    public void setCola1avatar(JScrollPane cola1avatar) {
        this.cola1avatar = cola1avatar;
    }

    public JScrollPane getCola1unshowmas() {
        return cola1unshowmas;
    }

    public void setCola1unshowmas(JScrollPane cola1unshowmas) {
        this.cola1unshowmas = cola1unshowmas;
    }

    public JScrollPane getCola2avatar() {
        return cola2avatar;
    }

    public void setCola2avatar(JScrollPane cola2avatar) {
        this.cola2avatar = cola2avatar;
    }

    public JScrollPane getCola2unshowmas() {
        return cola2unshowmas;
    }

    public void setCola2unshowmas(JScrollPane cola2unshowmas) {
        this.cola2unshowmas = cola2unshowmas;
    }

    public JScrollPane getCola3avatar() {
        return cola3avatar;
    }

    public void setCola3avatar(JScrollPane cola3avatar) {
        this.cola3avatar = cola3avatar;
    }

    public JScrollPane getCola3unshowmas() {
        return cola3unshowmas;
    }

    public void setCola3unshowmas(JScrollPane cola3unshowmas) {
        this.cola3unshowmas = cola3unshowmas;
    }

    public JScrollPane getColaganadoresavatar() {
        return colaganadoresavatar;
    }

    public void setColaganadoresavatar(JScrollPane colaganadoresavatar) {
        this.colaganadoresavatar = colaganadoresavatar;
    }

    public JScrollPane getColaganadoresunshowmas() {
        return colaganadoresunshowmas;
    }

    public void setColaganadoresunshowmas(JScrollPane colaganadoresunshowmas) {
        this.colaganadoresunshowmas = colaganadoresunshowmas;
    }

    public JButton getjButton1() {
        return jButton1;
    }

    public void setjButton1(JButton jButton1) {
        this.jButton1 = jButton1;
    }

    public JLabel getVictoriasAVT() {
        return VictoriasAVT;
    }

    public void setVictoriasAVT(JLabel VictoriasAVT) {
        this.VictoriasAVT = VictoriasAVT;
    }

    public JLabel getVictoriasUSM() {
        return VictoriasUSM;
    }

    public void setVictoriasUSM(JLabel VictoriasUSM) {
        this.VictoriasUSM = VictoriasUSM;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JScrollPane getRefuerzoavatar() {
        return refuerzoavatar;
    }

    public void setRefuerzoavatar(JScrollPane refuerzoavatar) {
        this.refuerzoavatar = refuerzoavatar;
    }

    public JScrollPane getRefuerzounshowmas() {
        return refuerzounshowmas;
    }

    public void setRefuerzounshowmas(JScrollPane refuerzounshowmas) {
        this.refuerzounshowmas = refuerzounshowmas;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Simulación.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Simulación.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Simulación.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Simulación.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Simulación().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgilidadAVT;
    private javax.swing.JLabel AgilidadUSM;
    private javax.swing.JTextArea Cola1AVT;
    private javax.swing.JTextArea Cola1USM;
    private javax.swing.JTextArea Cola2AVT;
    private javax.swing.JTextArea Cola2USM;
    private javax.swing.JTextArea Cola3AVT;
    private javax.swing.JTextArea Cola3USM;
    private javax.swing.JTextArea ColaGanadoresAVT;
    private javax.swing.JTextArea ColaGanadoresUSM;
    private javax.swing.JLabel CompetidorAVT;
    private javax.swing.JLabel CompetidorUSM;
    private javax.swing.JSpinner DuracionBatalla;
    private javax.swing.JLabel EstadoIA;
    private javax.swing.JLabel FuerzaAVT;
    private javax.swing.JLabel FuerzaUSM;
    private javax.swing.JLabel HabilidadAVT;
    private javax.swing.JLabel HabilidadUSM;
    private javax.swing.JLabel NombreCompetidorAVT;
    private javax.swing.JLabel NombreCompetidorUSM;
    private javax.swing.JTextArea RefuerzoAVT;
    private javax.swing.JTextArea RefuerzoUSM;
    private javax.swing.JLabel VictoriasAVT;
    private javax.swing.JLabel VictoriasUSM;
    private javax.swing.JLabel VidaAVT;
    private javax.swing.JLabel VidaUSM;
    private javax.swing.JScrollPane cola1avatar;
    private javax.swing.JScrollPane cola1unshowmas;
    private javax.swing.JScrollPane cola2avatar;
    private javax.swing.JScrollPane cola2unshowmas;
    private javax.swing.JScrollPane cola3avatar;
    private javax.swing.JScrollPane cola3unshowmas;
    private javax.swing.JScrollPane colaganadoresavatar;
    private javax.swing.JScrollPane colaganadoresunshowmas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane refuerzoavatar;
    private javax.swing.JScrollPane refuerzounshowmas;
    // End of variables declaration//GEN-END:variables
}
